### PR TITLE
t/159: The selected link element should not resemble the native selection

### LINKED ISSUE #159: Link highlight resembles the selection
image

You have to think for second to understand what's selected here.

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The selected link element should not resemble the native selection. Closes #159.

### CODE REVIEW

**Comment by dkonopka** [comment]
Still, I see some gaps 😢 In Chrome case I guess it's caused by native selection related to [descenders](https://en.wikipedia.org/wiki/Descender#/media/File:Descender.png).

### Chrome
screen shot 2018-03-22 at 13 58 15



### Firefox
screen shot 2018-03-22 at 13 54 49

**Comment by dkonopka** [comment]
☝️ I'm for it too. Another thing is how this `box-shadow` solution is rendered on Windows - probably also buggy or even more...

**Comment by oleq** [comment]
OK, let's drop the shadow then.

**Comment by Reinmar** [comment]
R- for now.

**Comment by dkonopka** [comment]
WFM 👍 

screen shot 2018-03-26 at 12 15 40

Still, we have this bug related to `span.ck-link-selected` with bigger font-sizes. 

Additional class on `<a>` element it is not a perfect solution because it contains extra `<span>` inside in font-size example (we should fix it then with `.ck-link-selected * { background: color}`).

### current

screen shot 2018-03-26 at 12 16 28

**Comment by oleq** [comment]
@dkonopka https://github.com/ckeditor/ckeditor5-link/issues/180

**Pull request merged**
