### PR TITLE
i/6415: Selected widget's outline should be visible when editor is in read-only

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: The selected widget's outline should be visible when the editor is read-only. Closes ckeditor/ckeditor5#6415.

---

image

### CODE REVIEW

**Comment by panr** [comment]
Should the blinking of the orange outline color be visible like that? 

outline

**Comment by oleq** [comment]
Probably not. Gonna take a look at it.

**Comment by oleq** [comment]
How about now @panr?

**Comment by panr** [comment]
LGTM 👌

**Pull request merged**
