### PR TITLE
Add  .ck-splitbutton to Theme customization

### PR DESCRIPTION
**Pull request by MCMicS**
add colors for .ck-splitbutton to use Track Changes with dark theme

### CODE REVIEW

**Comment by oleq** [comment]
@MCMicS What problem does this PR solve?

**Comment by MCMicS** [comment]
If you want to use dark theme (see https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/theme-customization.html) then the split button will be grey on hover actions

**Comment by MCMicS** [comment]
any Progress here?

**Comment by oleq** [comment]
Hi, @MCMicS! I'm sorry but we're in the middle of release at this moment and I didn't have time to check this out. 

If I got it correctly, this PR is only about the documentation (the UI color guide) only? It's not a direct bug fix?

**Comment by MCMicS** [comment]
@oleq yes thats right.

**Comment by oleq** [comment]
Everything's all right. Thanks @MCMicS!

**Pull request merged**
