### PR TITLE
t/135 Removed "vanilla" Lark 

### LINKED ISSUE #135: Does maintaining a vanilla and editor Lark in parallel make any sense?
## Status of things

ATM we have the "vanilla" Lark (see theme MT):

image

and the "editor" Lark:

image

next to each other. The later is implemented by `editorui.css`. 

## Why having two sub–Larks is a bad idea?

Although in the past it made some sense because "generic" buttons (e.g. in the link balloon) had different styles than the toolbar

image

ATM there's hardly any difference

image

The problem is that maintaining both of them is a waste of time. I tried to fix https://github.com/ckeditor/ckeditor5-theme-lark/issues/134 ASAP but I soon found out that to make both "themes" fixed, it would take some serious refactoring in variables, etc.. The "editor" Lark overrides the "vanilla" one in many places and thus the whole thing becomes more and more complex as new components arrive.

If we assumed that Lark always looks the same (just like the editor toolbar), things would become more straightforward and we could save some (considerable) amount of time. 

## Why having two sub–Larks is a good idea?

Nothing comes to my mind.

----

cc @Reinmar @dkonopka @wwalc

### PR DESCRIPTION
**Pull request by dkonopka**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Removed styles for `ck-editor-toolbar`. Closes #135.
Other: Removed border from `ck-button` class.
Tests: Wrapped buttons and icons in `ToolbarView` in manual theme test.

### CODE REVIEW

**Comment by oleq** [comment]
Some impressions and bugs:
* I'd get rid of these three variables too https://github.com/ckeditor/ckeditor5-theme-lark/blob/633bdc12a4ae59b5788df4aed8d669af1148ef26/theme/ckeditor5-ui/globals/_colors.css#L98-L100. The point of this refac is to remove the middle (vanilla) layer completely.
* I'd wrap all the buttons in the lark MT in `.ck-toolbar`. We can do that by code, creating a `ToolbarViews` to speed it up. ATM it's hard to tell what's going on 
image

**Comment by oleq** [comment]
The balloon should not have the same background as the toolbar
image

**Comment by dkonopka** [comment]
Ok, variables removed, manual tests updated, I've added ToolbarViews for every button/icon group.

@oleq Let's talk about balloon background, why (and when? :D) we decided to use two different backgrounds for toolbar and balloon? Currently, it looks really weird, maybe we should consider one for every panel in the editor?

### toolbar bg - hsl(0, 0%, 98%)
screen shot 2018-02-16 at 09 57 06
### balloon bg - hsl(0, 0%, 100%)
screen shot 2018-02-16 at 09 57 12

**Comment by oleq** [comment]
We never considered a balloon with a darker background when working on https://github.com/ckeditor/ckeditor5/issues/645. IMO white balloons provide a better contrast between the wall of edited text and the UI and that's a good enough reason. It's more evident when in the context

screen shot 2018-02-16 at 10 40 10
screen shot 2018-02-16 at 10 40 46

**Comment by oleq** [comment]
Anyway, we can discuss the topic in a separate issue. Let's focus on the task at hand and not touch the design we came up with.

**Comment by dkonopka** [comment]
Agree. I'll make follow-up then and bring back white background for the balloon.

**Pull request merged**
