### PR TITLE
i/6446: Fix the table selection background

### LINKED ISSUE #6446: The live preview of the table cell background should work with multiple-cell selection
## 📝 Provide detailed reproduction steps (if any)

When the selection is in a cell, it works just fine. But when we display selected cell styles for multi-selection, they override the background.

This is almost impossible to fix unless we drop selected table cells' backgrounds completely in favor of borders.

## 📃 Other details

Somehow but not directly related https://github.com/ckeditor/ckeditor5/issues/6425.

cc @panr 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Improved table cell background in multi selection. Closes ckeditor/ckeditor5#6446.

---

### Additional information

- From now on, user is able to see table cell background changes in the live preview.

### CODE REVIEW

**Review by oleq — COMMENTED** [review]
It looks awesome ♥️ 

The only glitch I found is on Firefox:



TBH, I can live with that. WDYT @Reinmar?

**Comment by Reinmar** [comment]
Agree. It looks awesome. The glitch on FF is fine. I'd only consider slightly more opaque overlay to make it a bit more visible.

**Comment by oleq** [comment]
> Agree. It looks awesome. The glitch on FF is fine. I'd only consider slightly more opaque overlay to make it a bit more visible.

It could be then too contrasty with a white cell background and distort the text color too much at the same time. ATM it looks fine I think
image

I played a little with the opacity of the overlay color (up to .6) and the `mix-blend-mode: multiply` and this is what it could look like.

Before:

Screenshot 2020-04-16 at 17 17 56

After:

**Comment by panr** [comment]
For me, selected items should be brighter (washed out). The same situation we have, ie: in Google Docs:

image

**Pull request merged**
