### PR TITLE
 Fixed inheriting font color in two colored icons

### LINKED ISSUE #148: Split button does not inherit the font color properly
Change the `--ck-color-base-text` to see the issue.

image

### PR DESCRIPTION
**Pull request by dkonopka**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Inheriting font color in two colored icons. Closes #148.

### CODE REVIEW

**Comment by dkonopka** [comment]
There is also an idea to use **[custom property CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/var)** and it will be everything alright:

in @ckeditor/ckeditor5-highlight/theme/highlight.css change:

```css
.ck-highlight-button svg path:not(.ck-icon__fill) {
	/* Do not inherit color from parent. */
	color: initial;
}
```

to
```css
.ck-highlight-button svg path:not(.ck-icon__fill) {
	/* Do not inherit color from parent. */
	color: var(--ck-color-base-text, initial);
}
```

**Comment by oleq** [comment]
I reviewed your fixes and I found out the actual root of the problem. It is the highlight feature which implements the icon coloring based on the `color` property cascade coming from `<button>` to `path.ck-icon__fill` in a tricky way, depending on the `.ck-highlight-button` class. 

For one thing, it's a hack. And, as a hack, it has just blown up.

Another thing is that it's totally non-reusable. It's enclosed in the highlight logic and no their packages will be able to use it to color their own icons.

So instead of patching a hack I propose a better architecture in https://github.com/ckeditor/ckeditor5-theme-lark/pull/152, which is re-usable and handles the problem.
screen shot 2018-02-22 at 13 13 28

**Comment by Reinmar** [comment]
Can this PR be closed (without merging) now?

**Comment by dkonopka** [comment]
Yes, oleq provided other solution (changes in UI) - so this PR is out-of-date.

**Pull request closed without merging**
