### PR TITLE
t/ckeditor5/816: Fixed border-radius of active dropdown button & panel.

### PR DESCRIPTION
**Pull request by dkonopka**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Removed common (left bottom & top corner) border-radius of dropdown button & panel. Closes [ckeditor/ckeditor5#816](https://github.com/ckeditor/ckeditor5/issues/816).

---

### Before:
screen shot 2018-02-19 at 12 19 37

### After:
screen shot 2018-02-19 at 12 01 24

### CODE REVIEW

**Comment by oleq** [comment]
image

The upper–left corner of the list item needs adjustment. You could also check if there's anything we can do to reduce the radius of the other list items' corners to get rid of that tiny white area.

**Comment by oleq** [comment]
Dropdowns can't have `overflow:hidden` because it breaks tooltips
image

**Comment by dkonopka** [comment]
@oleq I don't see any proper solution for `border-radius` inner `border-radius` maybe we can try with reducing it by 1px?

```css
.ck-list {
	list-style-type: none;
	background: var(--ck-color-list-background);
	
	/* https://github.com/ckeditor/ckeditor5-theme-lark/pull/146#issuecomment-366945243 */
	border-top-right-radius: calc( var(--ck-border-radius) - 1px );
}
```

screen shot 2018-02-20 at 14 30 24

**Comment by oleq** [comment]
OK, let's leave it as it is and focus on the merit of the issue then.

**Pull request merged**
